FROM node:18-alpine

WORKDIR /app

# Copy the backend code and dependencies installed by Jenkins
COPY backend ./backend

# Copy the frontend build generated by Jenkins
COPY frontend/build ./frontend/build

WORKDIR /app/backend

EXPOSE 5000

CMD ["npm", "start"]
